[tool.poetry]
name = "supermarket-offer-scanner"
version = "0.1.0"
description = ""
authors = ["Florian Kretschmer <entepotenz@gmail.com>"]
readme = "README.md"
packages = [{ include = "source" }]

[tool.poetry.dependencies]
python = "^3.10"
selenium = "4.17.2"
typer = "0.12.3"
pypdf = "4.2.0"

[tool.poetry.group.dev.dependencies]
black = "25.1.0"
pyhamcrest = "2.1.0"
pytest = "8.4.1"
ruff = "0.12.1"
yapf = "0.43.0"
mypy = "1.16.1"
flake8 = "7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
